### ISSUE TITLE
Split emulation projects from XboxDev

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/XboxDev#13]
nxdk was originally an idea to attract CTF players to XQEMU; hence it was hosted on XQEMU.
XQEMU developers then started XboxDevWiki to be able to work closer with Cxbx-Reloaded developers (maintain and develop the shared ecosystem together).
So eventually nxdk moved to XboxDev to split responsibility.
The Wiki also quickly attracted new projects and people almost entirely unrelated to emulation (Xbox-Linux, people working on XID hardware, people who just like to document Xbox history, ..).

As a result, XboxDev grew and has become more independent (> 350 Discord users).

However, at this point emulation is getting more popular.
Especially XQEMU infrastructure (developer IRC) is still linked to XboxDev Discord through #xqemu. There's also #user-support which is for both projects (although it's primarily based for XQEMU, as Cxbx-R has their own infrastructure, hence #cxbx-r is slow).
The few mentions of XQEMU and Cxbx-R on the Wiki and GitHub are not as problematic.

These emulation channels draw in end-users (non-developers) who distract from actual goals.

I think we are approaching the point where we should split XQEMU and Cxbx-R from XboxDev.

Nothing would really change, except that we wouldn't be highlighting them from XboxDev projects anymore. Each project would use their own communication infrastructure, but use XboxDev communication infrastructure for XboxDev projects.

The major benefit is that we can focus on attracting developers, improve response times for user-support and we can avoid treating non-XQEMU projects "unfairly" (as XQEMU is omnipresent in all XboxDev channels, possibly driving others away; also slightly related #12 ).

XboxDev would still recommend developers to test their tools in XQEMU (and possibly Cxbx-R if HLE works for it) so these projects would also still benefit directly.

**Comment by GXTX** [comment]
I don't think it's a bad idea to move XboxDev eco away but one problem that's going to be immediate is there's a lot of discussion in those channels as well as just small tidbits of useful information. Something I think you'll bring up in response to that is if the information was that useful it would've likely been posted somewhere like the wiki or in various projects issue pages, but I still think there's good information lurking in those channels.

**Comment by JayFoxRox** [comment]
> one problem that's going to be immediate is there's a lot of discussion in those channels as well as just small tidbits of useful information.

Yes.

> Something I think you'll bring up in response to that is if the information was that useful it would've likely been posted somewhere like the wiki or in various projects issue pages, but I still think there's good information lurking in those channels.

Yes. But as-is, a lot of that information is also lost in the emulation channel logs. In other cases it's only seen by one group of developers (mainly XQEMU), which creates information asymmetry.
Other discussions get derailed by users and other conversations.

Also if you look at *who* is providing that information in the existing emulation channels, you'll find that it's typically developers who'd still be on XboxDev even after the split (People like LukeUsher, mborgerson or myself). So there's no issue in just switching channels.
We'll just have to be more strict and would direct those people to XboxDev. But I think that's actually beneficial, as we'd only re-direct developers. Even if someone doesn't want to join, others could still forward their information.

My experience with Citra (3DS emulator) was that people knew when to switch to https://www.3dbrew.org/ (their XboxDev counterpart), and generally most research was being discussed in the correct channels.

**Comment by mborgerson** [comment]
Since CXBX-R already has an independent Discord server and the `#cxbx-r` channel on XboxDev goes largely unused, I think this discussion is mostly about whether XQEMU should be split from the XboxDev Discord server. So I'll focus on that.

Here's what I like about the idea: This could give users a space to more loosely talk about XQEMU, without feeling like they're interrupting other development related discussion, or in worry of being topic policed (which happens far too often IMO). Our current `#xqemu` room is very much focused on development, and this could give users as better place to ask questions. We could create new channels such as `#showcase` to show off screenshots/videos, `#multiplayer` for people to organize networked games, etc. 

Here's what I prefer to keep about our existing setup: XboxDev Discord is focused on research & development of the original Xbox, including emulation. As such, there is often conversations which move between rooms as the discussion evolves (from `#xqemu` to `#research` or back). I think the existing `#xqemu` development channel should remain on the XboxDev Discord server (and still linked to the IRC channel) to keep it development focused. The new Discord server would focus exclusively on users (and users helping other users).

Here's some potential pain points: Having another Discord server means maintaining another Discord server. This problem is solved with trusted moderators who can enforce the community standards that have been established for XboxDev.  It also means having to check multiple servers for new messages. We also will probably need to explain the difference between the two servers multiple times, and try to migrate people to the new server.

**Comment by PatrickvL** [comment]
Allow me to add this: the cxbx-r channel was created on the XboxDev discord server to avoid high volumes of end-user talk polluting the cxbx-dev channel on the Cxbx-Reloaded discord server. If indeed end users are slowly taking over the XboxDev channels too, then I'd agree with the split proposed in the opening post. But on the other hand, won't users just keep chasing development talk? Would it be an acceptable alternative to mark development channels read only, and writable for actual developers? (People that have been labelled as such, or contributed at least one commit, or whatever criteria is appropriate)

**Comment by mborgerson** [comment]
A new Discord server has been created specifically for the XQEMU user community at https://discord.gg/4aZYj74. The XboxDev `#user-support` channel will now be moved to a read-only state. Further user discussion should be directed to the respective XQEMU/CXBX-R Discord servers.
